// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF4DD0iEQaSSGmY8cSd8PY7IKcJSfFpI4',
    appId: '1:1037726524082:web:1e7a7fa69b281de2e71fab',
    messagingSenderId: '1037726524082',
    projectId: 'manajemenwaktu-f7961',
    authDomain: 'manajemenwaktu-f7961.firebaseapp.com',
    databaseURL: 'https://manajemenwaktu-f7961-default-rtdb.firebaseio.com',
    storageBucket: 'manajemenwaktu-f7961.appspot.com',
    measurementId: 'G-L87J6P3LG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVxsF1qlZRstYEiVYctCqIFATEpiY47vs',
    appId: '1:1037726524082:android:49820e812e003c80e71fab',
    messagingSenderId: '1037726524082',
    projectId: 'manajemenwaktu-f7961',
    databaseURL: 'https://manajemenwaktu-f7961-default-rtdb.firebaseio.com',
    storageBucket: 'manajemenwaktu-f7961.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDptEzgn4VGcyKGcUCYMPRDx3bE18DVPFM',
    appId: '1:1037726524082:ios:d1ff39aa8c8970cfe71fab',
    messagingSenderId: '1037726524082',
    projectId: 'manajemenwaktu-f7961',
    databaseURL: 'https://manajemenwaktu-f7961-default-rtdb.firebaseio.com',
    storageBucket: 'manajemenwaktu-f7961.appspot.com',
    iosBundleId: 'com.example.manajemenWaktu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDptEzgn4VGcyKGcUCYMPRDx3bE18DVPFM',
    appId: '1:1037726524082:ios:d1ff39aa8c8970cfe71fab',
    messagingSenderId: '1037726524082',
    projectId: 'manajemenwaktu-f7961',
    databaseURL: 'https://manajemenwaktu-f7961-default-rtdb.firebaseio.com',
    storageBucket: 'manajemenwaktu-f7961.appspot.com',
    iosBundleId: 'com.example.manajemenWaktu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF4DD0iEQaSSGmY8cSd8PY7IKcJSfFpI4',
    appId: '1:1037726524082:web:517b2b5539d89c19e71fab',
    messagingSenderId: '1037726524082',
    projectId: 'manajemenwaktu-f7961',
    authDomain: 'manajemenwaktu-f7961.firebaseapp.com',
    databaseURL: 'https://manajemenwaktu-f7961-default-rtdb.firebaseio.com',
    storageBucket: 'manajemenwaktu-f7961.appspot.com',
    measurementId: 'G-2LV6BDTKV7',
  );
}
